#!/usr/bin/env bash
openssl aes-256-cbc -K $encrypted_a626daabe3df_key -iv $encrypted_a626daabe3df_iv -in ./.travis/deploy_key.enc -out ${TRAVIS_BUILD_DIR}/.travis/deploy_key -d
chmod 600 ${TRAVIS_BUILD_DIR}/.travis/deploy_key
mv ${TRAVIS_BUILD_DIR}/.travis/deploy_key ~/.ssh/id_rsa
cat ${TRAVIS_BUILD_DIR}/.travis/ssh_config >> ~/.ssh/config
